version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    container_name: todo_list
    restart: unless-stopped
    ports:
      - ${DOCKER_WEB_PORT-7000}:80
    volumes:
      - ./backend:/app/backend:z
    environment:
      MODULE_NAME: backend.api.entrypoint
    env_file:
      - .env
    command: bash /start-reload.sh

  database:
    image: postgres:15-alpine
    container_name: database
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}
    volumes:
      - ../fastapi-hexagonal-resources/database:/var/lib/postgresql/data:z
      - ../fastapi-hexagonal-resources/database_backup:/home/database_backup:z
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fastapi-hexagonal}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}