version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    container_name: todo_list
    restart: unless-stopped
    ports:
      - ${DOCKER_WEB_PORT-7000}:80
    volumes:
      - .:/user/src/app:z
    environment:
      MODULE_NAME: backend.api.entrypoint
    command: bash /start-reload.sh